project_id = "prqvohcuhvzokfqodmfe"

[functions.wordpress-sync]
verify_jwt = true

[functions.wordpress-push]
verify_jwt = true

[functions.wordpress-test-connection]
verify_jwt = true

[functions.wordpress-taxonomy]
verify_jwt = true

[functions.update-wp-credentials]
verify_jwt = true

